easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Zone
       - App\Entity\Planche
       - App\Entity\Serre
       - App\Entity\Legume
       - App\Entity\Tache
       - App\Entity\Rotation
